# Generated by Django 4.0.5 on 2022-07-02 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alergy',
            table='alergies',
        ),
        migrations.AlterModelTable(
            name='alergy_drink',
            table='alergy_drink',
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='drink',
            table='drinks',
        ),
        migrations.AlterModelTable(
            name='image',
            table='images',
        ),
        migrations.AlterModelTable(
            name='menu',
            table='menus',
        ),
        migrations.AlterModelTable(
            name='nutrition',
            table='nutritions',
        ),
        migrations.AlterModelTable(
            name='size',
            table='sizes',
        ),
    ]
