# Generated by Django 4.0.5 on 2022-07-02 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_alergy_table_alter_alergy_drink_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='caffeine_mg',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='drink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.drink'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='one_serving_kcal',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
